(defun add-function-brackets()
  (interactive)
  (insert "\n")
  (insert "{")
  (execute-kbd-macro [?\t])
  (insert "\n")
  (push-mark)
  (insert "\n")
  (insert "}")
  (execute-kbd-macro [?\t])
  (goto-char (mark))
  (execute-kbd-macro [?\t]))
