(defun create-personal-welcome-buffer()
  (interactive)
  (set-buffer (get-buffer-create "welcome"))
  (insert "Welcome back, Jared.\n")
  (insert "It's another beautiful day for Emacs.\n")
  (goto-char (point-max))
  (switch-to-buffer "welcome"))
